'use client'
import Navigation from '@/components/layout/navigation'
import { config } from '@/services/connect-kit-client'
import { ConnectKitProvider } from 'connectkit'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { WagmiConfig } from 'wagmi'
import './globals.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <WagmiConfig config={config}>
      <ConnectKitProvider>
        <html lang='en'>
          <body className={`${inter.className} min-h-screen`}>
            <Navigation />
            {children}
          </body>
        </html>
      </ConnectKitProvider>
    </WagmiConfig>
  )
}
